### ISSUE TITLE
Server + DB Issues

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Server#5]
1. All passwords on DB must be encrypted before being stored into the database

2. Users who are assigned with a roleID 4 must have a wallet created for them, what is the current trigger for the generation of a wallet record for the native users?

3. When storing names in the DB, you dont store full names, you store either first name and then last name or you store full names as lower cases.

**Comment by ptxd** [comment]
passwords are encrypted -- need test to pass
wallet created when new user signs up --- need to pass test

pending -- name convention

**Comment by pavanmaind** [comment]
1. We have encrypted the passwords before storing in db.
2. We are creating wallet for users with roleId 4.
3. We have added two more fields in db to store firstName and lastName seperately.
