### ISSUE TITLE
Body Parser -- Update Package

### ISSUE THREAD

**Issue by ptxd** [swiperewards/Server#6]
Hi,

Please resolve errors when you get them, they are simple to fix.

Upgrade body-parser package to 1.18.3 and reinstall the package.

Thanks!

**Comment by pavanmaind** [comment]
Hi,
This is done, upgraded to 1.18.3

**Comment by ptxd** [comment]
Did you run npm install before deployment?

**Comment by pavanmaind** [comment]
Hey Shon, I have run the command "npm install body-parser@latest --save" command. However we have not deployed the changes on ec2 yet, we will deploy it soon.

**Comment by ptxd** [comment]
Issue closed with the new branches
